docs:
  categorize_library: true
  categorize_verify: false
  html: false
  toc: false
plugins:
- jemoji
- jekyll-remote-theme
remote_theme: rsk0315/minima

title: えびちゃんライブラリ
author: えびちゃん
# description: "[えびちゃん](https://twitter.com/rsk0315_h4x) のライブラリです。[online-judge-verify-helper](https://github.com/kmyk/online-judge-verify-helper) で管理されています。"
# footer_description: "えびちゃんかわいいね。にゃんにゃん。"
description: "えびちゃんかわいいね。にゃんにゃん。"

# minima:
#   social_links:
#     twitter: rsk0315_h4x

github:
  project_tagline: "[えびちゃん](https://twitter.com/rsk0315_h4x) のライブラリです。[online-judge-verify-helper](https://github.com/kmyk/online-judge-verify-helper) で管理されています。"
