docs:
  categorize_library: true
  categorize_verify: false
  html: false
  toc: false
plugins:
- jemoji
- jekyll-remote-theme
remote_theme: rsk0315/minima

title: えびちゃんライブラリ
author: "<a href=\"https://twitter.com/rsk0315_h4x\">えびちゃん</a>"
description: "えびちゃんのライブラリです。[online-judge-verify-helper](https://github.com/kmyk/online-judge-verify-helper) で管理されています。"
footer_description: "えびちゃんかわいいね。にゃんにゃん。"

# minima:
#   social_links:
#     twitter: rsk0315_h4x
