docs:
  categorize_library: true
  categorize_verify: false
  html: false
  toc: false
plugins:
- jemoji
- jekyll-remote-theme
remote_theme: rsk0315/minima

title にゃー
author: にゃん？
description: にゃん
social-network-links:
  twitter: rsk0315_h4x
share-links-active:
  twitter: true
